# Use an official Node.js runtime as a parent image
FROM node:14-alpine as build

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files into the container
COPY package*.json ./

# Install the dependencies in the container
RUN npm install

# Copy the rest of the application files into the container
COPY . .

# Build the frontend for production
RUN npm run build

# Use the official Nginx image as a parent image
FROM nginx:alpine

# Copy the custom nginx.conf file into the Nginx container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the build files into the Nginx container
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to the host machine
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
