version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
